In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import torch as pt
import numpy as np
import os, json
from tqdm import tqdm

tqdm.pandas()

In [2]:
train_set =  pd.read_pickle("dataset/train.bin.zst")
dev_set =  pd.read_pickle("dataset/dev.bin.zst")
test_set =  pd.read_pickle("dataset/test.bin.zst")

In [3]:
def get_list_id():
    list_id = []
    for i in range(0, len(train_set)):
        list_id.append(train_set[i].id)
    for i in range(0, len(dev_set)):
        list_id.append(dev_set[i].id)
    for i in range(0, len(test_set)):
        list_id.append(test_set[i].id)
    return list_id

In [58]:
# non if non medata
# read the metadata if metadata and add to the dataset
def read_metadata(path):

    json_files = [pos_json for pos_json in os.listdir(path) if pos_json.endswith('.json')]

    metadata = {}

    for i in range(len(json_files)):
        f = open(path+"/"+json_files[i], encoding='utf-8')
        # print(json_files[i])
        data = json.load(f,strict=False)
        # if ( json_files[i] == "123534.json"):
        #     print(type(data["director"]))
        #     print("yes")
        if "director" in data:
            # print(data)
            if type(data["director"]) == list:
                metadata.update({json_files[i][:-5]: [d['name'] for d in data["director"]]})
            else:
                metadata.update({json_files[i][:-5]: data["director"]["name"]})
        elif "creator" in data:
            if type(data["creator"]) == list:
                metadata.update({json_files[i][:-5]: [d['name'] for d in data["creator"]]})
            else:
                metadata.update({json_files[i][:-5]: data["creator"]["name"]})
        else:
            metadata.update({json_files[i][:-5]: "none"})
        
        f.close()
        # metadata.update({json_files[i][:-5]: data["director"]["name"]})

    return metadata

In [60]:

metadata = read_metadata("moviejson")
metadata["229864"]

'Joseph Kosinski'

In [111]:
# train_set.movie="275149"
train_set.loc[train_set["movie"] == "275149"]

Empty DataFrame
Columns: [movie, name, user_id, note, commentaire]
Index: []

In [112]:
if str(229864) in metadata: # 229864 275149
    print("yes")

yes

In [113]:
train = train_set.copy()

In [61]:
# train_set = train_set["commentaire"]+metadata[train_set["review_id"]]
def addGerne(dataset):
    for i in dataset.index:
        # train_set[i].commentaire = train_set[i].commentaire + metadata[train_set[i].review_id]
        # print(train_set.loc[i])
        # print(metadata[str(train_set.loc[i].movie)])
        # if ( train_set.loc[i].movie == 229864):
        #     print("yes")
        if str(dataset.loc[i].movie) in metadata:
            if type(metadata[str(dataset.loc[i].movie)])==list:
                # print("list")
                # print(str(metadata[str(train.loc[i].movie)]).strip('[]') + " : " + train.loc[i].commentaire)
                # print()
                dataset.at[i,'commentaire'] = ', '.join(metadata[str(dataset.loc[i].movie)]) + " : " + dataset.loc[i].commentaire
            else:
                dataset.at[i,'commentaire'] = metadata[str(dataset.loc[i].movie)] + " : " + dataset.loc[i].commentaire

        # print(type(train_set.loc[i].commentaire))
        #

In [62]:
train.loc[58145147].commentaire

NameError: name 'train' is not defined

In [116]:
train

,movie,name,user_id,note,commentaire
review_id,,,,,
58145147,229864,AM11,Z20051105131449940367618,4.0,"""Ce n'est pas ce qui se trouve en face de vous..."
59303833,229864,this is my movies,Z20051220181957240298347,3.5,"(...) En soi, je n'ai rien contre ce genre de ..."
61916672,229864,Shephard69,Z20121226180301760912584,4.5,"Pour sa troisième réalisation après ""Tron, l'h..."
1000190786,229864,Tayop,Z20121022182542230468657,3.0,Joseph Kosinski offre de nouvelles images ébou...
59207755,229864,ned123,Z20061211223247607682175,3.5,J'ai vu un film... qui traite d'un drame humai...
...,...,...,...,...,...
55820729,245551,Wally L,Z20121109004006553333277,4.0,super realisation et quelques bon acteurs. ce...
1001840194,245551,r@ch,Z20100726110927837577369,3.0,Film visuellement très beau et mis en musique ...
56242470,245551,Kaiser D.,Z20170721223303710182536,3.5,parti d'une histoire qui parait pour nous bana...
58174196,245551,Florent A.,Z20161204004443590736237,3.0,"Je suis mitigé sur ce film.d un coté,j ai plut..."
1006358741,245551,NSI N.,Z20170408073937420327568,3.5,un bon film Netflix pour une fois . le scénar...

In [63]:
train = train_set.copy()
addGerne(train)

In [64]:
train

,movie,name,user_id,note,commentaire
review_id,,,,,
58145147,229864,AM11,Z20051105131449940367618,4.0,"Joseph Kosinski : ""Ce n'est pas ce qui se trou..."
59303833,229864,this is my movies,Z20051220181957240298347,3.5,"Joseph Kosinski : (...) En soi, je n'ai rien c..."
61916672,229864,Shephard69,Z20121226180301760912584,4.5,Joseph Kosinski : Pour sa troisième réalisatio...
1000190786,229864,Tayop,Z20121022182542230468657,3.0,Joseph Kosinski : Joseph Kosinski offre de nou...
59207755,229864,ned123,Z20061211223247607682175,3.5,Joseph Kosinski : J'ai vu un film... qui trait...
...,...,...,...,...,...
55820729,245551,Wally L,Z20121109004006553333277,4.0,Justin Tipping : super realisation et quelques...
1001840194,245551,r@ch,Z20100726110927837577369,3.0,Justin Tipping : Film visuellement très beau e...
56242470,245551,Kaiser D.,Z20170721223303710182536,3.5,Justin Tipping : parti d'une histoire qui para...
58174196,245551,Florent A.,Z20161204004443590736237,3.0,Justin Tipping : Je suis mitigé sur ce film.d ...
1006358741,245551,NSI N.,Z20170408073937420327568,3.5,Justin Tipping : un bon film Netflix pour une ...

In [65]:

dev = dev_set.copy()
for i in dev.index:
    # train_set[i].commentaire = train_set[i].commentaire + metadata[train_set[i].review_id]
    # print(train_set.loc[i])
    # print(metadata[str(train_set.loc[i].movie)])
    # if ( train_set.loc[i].movie == 229864):
    #     print("yes")
    if str(dev.loc[i].movie) in metadata:
        if type(metadata[str(dev.loc[i].movie)])==list:
            # print("list")
            # print(str(metadata[str(train.loc[i].movie)]).strip('[]') + " : " + train.loc[i].commentaire)
            # print()
            dev.at[i,'commentaire'] = ', '.join(metadata[str(dev.loc[i].movie)]) + " : " + dev.loc[i].commentaire
        else:
            dev.at[i,'commentaire'] = metadata[str(dev.loc[i].movie)] + " : " + dev.loc[i].commentaire

    # print(type(train_set.loc[i].commentaire))
        #

In [66]:

test = test_set.copy()
addGerne(test)

In [67]:
dev

,movie,name,user_id,note,commentaire
review_id,,,,,
57113853,244430,I'm A Rocket Man,Z20150411212834470532236,5.0,Bourlem Guerdjou : Ce téléfilm est tout simple...
53044607,244430,apotheme,Z20070228015331953348969,3.5,Bourlem Guerdjou : Une fiction convaincainte q...
60265420,244430,Cronenbergfansoff,Z20170707170528043187781,4.0,"Bourlem Guerdjou : Énorme ce film, parmi les m..."
55880325,244430,willycopresto,Z20120217141238760128499,2.0,"Bourlem Guerdjou : ""Mario, 13 ans pour toujour..."
53015074,244430,atomewarrior,Z20110303190024017478821,5.0,"Bourlem Guerdjou : Un film choque, coups de po..."
...,...,...,...,...,...
59620693,221892,Fabio C.,Z20151005194626740254489,3.0,Xavier Beauvois : Après Le Petit Lieutenant et...
47495619,221892,Bernard L.,Z20150226232126323734384,2.5,Xavier Beauvois : Dommage : Des scènes qui tr...
45417182,221892,montezy,Z20100224224417197559762,4.0,Xavier Beauvois : un film lent et poétique.......
1002780563,221892,Eric L.,Z20160616161509357189631,0.5,Xavier Beauvois : Quand Une Musique de film p...
45412505,221892,Emmanuelle D.,Z20150111190802490303521,0.5,Xavier Beauvois : Ce film est pour moi très de...

In [124]:
train.to_csv("dataset/train.csv")
dev.to_csv("dataset/dev.csv")
test.to_csv("dataset/test.csv")